package com.itheima.service.impl;
import com.itheima.mapper.*; import com.itheima.pojo.*; import com.itheima.service.BorrowRecordService; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class BorrowRecordServiceImpl implements BorrowRecordService {
 @Autowired BorrowRecordMapper m; @Autowired UserMapper users;
 private static void bad(boolean b,String s){if(b)throw new RuntimeException(s);} private BorrowRecord record(Integer id){BorrowRecord r=m.lock(id);bad(r==null,"借用记录不存在");return r;}
 @Transactional public void apply(Integer uid,Integer did,String purpose,LocalDateTime expected,String remark){bad(did==null||did<1,"设备参数无效");bad(purpose==null||purpose.trim().length()<2||purpose.trim().length()>500,"请填写 2-500 字的借用用途");bad(expected==null||!expected.isAfter(LocalDateTime.now()),"预计归还时间必须晚于当前时间");Device d=m.lockDevice(did);bad(d==null,"设备不存在");bad(!"在库".equals(d.getStatus()),"该设备当前不在库，无法申请借用");bad(m.activeCount(did)>0,"该设备已有待处理借用记录");User u=users.findById(uid);bad(u==null,"用户不存在");BorrowRecord r=new BorrowRecord();r.setDeviceId(did);r.setBorrowerId(uid);r.setPurpose(purpose.trim());r.setExpectedReturnTime(expected);r.setRemark(remark);r.setStatus("待审核");r.setBorrowerName(u.getRealName()==null||u.getRealName().isBlank()?u.getUsername():u.getRealName());r.setBorrowerPhone(u.getPhone());r.setBorrowerIdentity(u.getStudentNo()==null||u.getStudentNo().isBlank()?u.getUsername():u.getStudentNo());m.insert(r);}
 public List<BorrowRecord> mine(Integer uid){m.markOverdue();return m.mine(uid);} public List<BorrowRecord> admin(){m.markOverdue();return m.admin();} public BorrowRecord active(Integer id){m.markOverdue();return m.active(id);}
 @Transactional public void approve(Integer id,Integer uid){BorrowRecord r=record(id);bad(!"待审核".equals(r.getStatus()),"该申请已被处理");Device d=m.lockDevice(r.getDeviceId());bad(d==null||!"在库".equals(d.getStatus()),"设备已不可借用");m.approve(id,uid);m.setDeviceStatus(d.getId(),"已借出");}
 @Transactional public void reject(Integer id,Integer uid,String reason){BorrowRecord r=record(id);bad(!"待审核".equals(r.getStatus()),"该申请已被处理");bad(reason==null||reason.trim().length()<2,"请填写拒绝原因");m.reject(id,uid,reason.trim());}
 @Transactional public void requestReturn(Integer id,Integer uid,String remark){BorrowRecord r=record(id);bad(!uid.equals(r.getBorrowerId()),"只能归还自己的借用设备");bad(!"借用中".equals(r.getStatus())&&!"逾期".equals(r.getStatus()),"当前状态不能申请归还");m.requestReturn(id,remark);}
 @Transactional public void confirm(Integer id,Integer uid,String status,String note){BorrowRecord r=record(id);bad(!"待归还确认".equals(r.getStatus()),"该归还记录已被处理");bad(!"在库".equals(status)&&!"维修中".equals(status)&&!"报废".equals(status),"归还后设备状态只能是“在库”、“维修中”或“报废”");Device d=m.lockDevice(r.getDeviceId());bad(d==null||!"已借出".equals(d.getStatus()),"设备状态异常，无法确认归还");m.confirm(id,uid,status,note);m.setDeviceStatus(d.getId(),status);}
}
