package com.itheima.controller;
import com.itheima.anno.RequireAdmin; import com.itheima.pojo.*; import com.itheima.service.BorrowRecordService; import com.itheima.utils.ThreadLocalUtil; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*;
@RestController @RequestMapping("/borrow") public class BorrowRecordController {
 @Autowired BorrowRecordService service; @SuppressWarnings("unchecked") private Integer uid(){return (Integer)((Map<String,Object>)ThreadLocalUtil.get()).get("id");}
 @PostMapping public Result apply(@RequestBody Map<String,Object> b){Integer d=b.get("deviceId")==null?null:Integer.valueOf(String.valueOf(b.get("deviceId")));LocalDateTime t=b.get("expectedReturnTime")==null?null:LocalDateTime.parse(String.valueOf(b.get("expectedReturnTime")));service.apply(uid(),d,String.valueOf(b.getOrDefault("purpose","")),t,(String)b.get("remark"));return Result.success();}
 @GetMapping("/my") public Result<List<BorrowRecord>> mine(){return Result.success(service.mine(uid()));} @GetMapping("/admin/list") @RequireAdmin public Result<List<BorrowRecord>> admin(){return Result.success(service.admin());} @GetMapping("/device/{id}/active") public Result<BorrowRecord> active(@PathVariable Integer id){return Result.success(service.active(id));}
 @PutMapping("/{id}/approve") @RequireAdmin public Result approve(@PathVariable Integer id){service.approve(id,uid());return Result.success();} @PutMapping("/{id}/reject") @RequireAdmin public Result reject(@PathVariable Integer id,@RequestBody Map<String,String>b){service.reject(id,uid(),b.get("rejectReason"));return Result.success();}
 @PostMapping("/{id}/return-request") public Result ret(@PathVariable Integer id,@RequestBody(required=false) Map<String,String>b){service.requestReturn(id,uid(),b==null?null:b.get("remark"));return Result.success();} @PutMapping("/{id}/confirm-return") @RequireAdmin public Result confirm(@PathVariable Integer id,@RequestBody Map<String,String>b){service.confirm(id,uid(),b.get("returnDeviceStatus"),b.get("returnCheckNote"));return Result.success();}
}
